"""empty message

Revision ID: f4d749b2e5a0
Revises: 
Create Date: 2024-09-21 08:57:23.473120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4d749b2e5a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('phone_contact', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('blood_group', sa.String(length=3), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('last_donated', sa.Date(), nullable=True),
    sa.Column('medical_history', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_whatsapp')
    )
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('fax', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_id')
    )
    op.create_table('blood_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=True),
    sa.Column('blood_type', sa.String(length=3), nullable=False),
    sa.Column('units_requested', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=50), nullable=True),
    sa.Column('patient_name', sa.String(length=100), nullable=True),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donor_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blood_request_id', sa.Integer(), nullable=True),
    sa.Column('donor_id', sa.Integer(), nullable=True),
    sa.Column('response', sa.String(length=10), nullable=True),
    sa.Column('date_responded', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_request.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donor_response')
    op.drop_table('blood_request')
    op.drop_table('hospital')
    op.drop_table('donor')
    # ### end Alembic commands ###
